"""
Agent controller — orchestrates all tools and decides LLM mode.

Flow for EVERY query:
  1. DB interaction check  (always — deterministic, ground truth)
  2. Drug profile fetch    (always — used as LLM context)
  3. RAG retrieval         (always for UNKNOWN; also for known to enrich explanation)
  4. LLM call              (always — but mode differs):
       • severity KNOWN    → explain_known_interaction()  — simplifies DB result
       • severity UNKNOWN  → assess_unknown_interaction() — full reasoning + warning

The DB result is NEVER overridden. The LLM only explains or fills gaps.
"""
import logging
from app.services.interaction_service import check_interaction
from app.services.drug_info_service import get_drug_info
from app.services.retrieval_service import retrieve_context
from app.llm.llm_provider import explain_known_interaction, assess_unknown_interaction

log = logging.getLogger(__name__)

_ADVISORY_WARNING = (
    "⚠️  AI-generated advisory — database has no confirmed severity for this combination. "
    "This analysis is based on pharmacological context only and has NOT been clinically validated. "
    "Consult a licensed healthcare professional before making any medication decisions."
)

_KNOWN_DISCLAIMER = (
    "This explanation was generated by AI to simplify a confirmed database result. "
    "Always consult a healthcare professional before changing your medications."
)

_DB_KNOWN = {"HIGH", "MODERATE", "LOW"}


def handle_interaction_query(drug1: str, drug2: str) -> dict:
    """
    Main agent entry point. Always returns an LLM-enriched response.
    """
    # ── Step 1: Deterministic DB check ────────────────────────────────────────
    db_result = check_interaction(drug1, drug2)
    severity  = db_result["severity"]
    resolved1 = db_result.get("resolved1") or drug1
    resolved2 = db_result.get("resolved2") or drug2
    rxcui1    = (db_result.get("rxcuis1") or [None])[0]
    rxcui2    = (db_result.get("rxcuis2") or [None])[0]

    log.info(f"DB result [{severity}]: {drug1} + {drug2}")

    # ── Step 2: Always fetch drug profiles for LLM context ────────────────────
    context_parts: list[str] = []
    info1 = get_drug_info(drug1)
    info2 = get_drug_info(drug2)
    if info1:
        _append_drug_context(context_parts, info1)
    if info2:
        _append_drug_context(context_parts, info2)

    # ── Step 3: RAG retrieval ──────────────────────────────────────────────────
    # Always retrieve — richer context = better plain-English explanation
    rag_context = retrieve_context(
        drug1=resolved1,
        drug2=resolved2,
        rxcui1=rxcui1,
        rxcui2=rxcui2,
    )
    if rag_context:
        context_parts.append(rag_context)

    full_context = "\n\n".join(context_parts)

    # ── Step 4: LLM — mode depends on severity ────────────────────────────────
    if severity in _DB_KNOWN:
        # Known severity: LLM explains the confirmed result in plain English
        llm_result = explain_known_interaction(
            drug1=resolved1,
            drug2=resolved2,
            severity=severity,
            description=db_result.get("description") or "",
            context=full_context,
        )
        return {
            "drug1":          drug1,
            "drug2":          drug2,
            "resolved_drug1": resolved1,
            "resolved_drug2": resolved2,
            "severity":       severity,
            "description":    db_result.get("description"),
            "source":         db_result.get("source") or "database",
            "confidence":     "known",
            "llm_assessment": llm_result,
            "warning":        _KNOWN_DISCLAIMER,
        }

    else:
        # UNKNOWN or NOT_FOUND: agent does full reasoning with warning
        log.info(f"Severity UNKNOWN — agent doing full pharmacology assessment")
        llm_result = assess_unknown_interaction(
            drug1=resolved1,
            drug2=resolved2,
            context=full_context,
        )
        return {
            "drug1":          drug1,
            "drug2":          drug2,
            "resolved_drug1": resolved1,
            "resolved_drug2": resolved2,
            "severity":       severity,
            "description":    db_result.get("description"),
            "source":         "llm_fallback",
            "confidence":     "dataset_missing",
            "llm_assessment": llm_result,
            "warning":        _ADVISORY_WARNING,
        }


def _append_drug_context(parts: list[str], info: dict) -> None:
    """Format a drug profile into a concise context block for the LLM."""
    lines = [f"Drug: {info['name']}"]
    if info.get("drug_class"):
        lines.append(f"Class: {info['drug_class']}")
    if info.get("indication"):
        lines.append(f"Used for: {info['indication'][:300]}")
    if info.get("mechanism"):
        lines.append(f"Mechanism: {info['mechanism'][:400]}")
    if info.get("pharmacology"):
        lines.append(f"Pharmacology: {info['pharmacology'][:300]}")
    if info.get("side_effects"):
        lines.append(f"Side effects: {info['side_effects'][:250]}")
    parts.append("\n".join(lines))
